name: dufs-broker
services:
  app:
    image: allape/dufs-broker:latest
    container_name: dufs-broker
    restart: unless-stopped
    ports:
      - "2021:2021"
      - "50000-50100:50000-50100"
    environment:
      DUBROKER_DUFS_SERVER: "http://localhost:5000"
      DUBROKER_ADDRESS: ":2021"
